version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      # Fixed the download links to use 'amd64' instead of '64bit'
      - wget https://github.com/gohugoio/hugo/releases/download/v0.121.1/hugo_extended_0.121.1_linux-amd64.tar.gz
      - tar -xzf hugo_extended_0.121.1_linux-amd64.tar.gz
      - mv hugo /usr/local/bin/
  build:
    commands:
      - echo Build started on `date`
      - hugo --minify
  post_build:
    commands:
      - aws s3 sync public/ s3://amzn-for-demo --region eu-north-1
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'public'